name: Linting

env:
    POETRY_VERSION: "1.4.0"

on:
    pull_request:
        types: [opened, reopened, synchronize]
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    run-tests:
        name: Python linters
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Set up Poetry
              run: |
                  pip install poetry==${{ env.POETRY_VERSION }}

            - name: Install
              run: |
                  poetry install

            - name: Show info
              run: |
                  printenv PATH
                  poetry env info

            # - name: Flake8
            #   run: |
            #       poetry run flake8 docs src tests

            # - name: Ruff
            #   run: |
            #       poetry run ruff check docs src tests

            # - name: Pylint
            #   run: |
            #       poetry run pylint src tests

            # - name: Mypy
            #   run: |
            #       poetry run mypy src tests

            - name: Pyroma
              run: |
                  poetry run pyroma .

            - name: Check poetry
              run: |
                  poetry check
                  poetry lock --check
